packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@eslint/js': ^9.36.0
  '@tailwindcss/typography': ^0.5.19
  '@tanstack/react-table': ^8.21.3
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
  '@typescript-eslint/eslint-plugin': ^8.45.0
  '@typescript-eslint/parser': ^8.45.0
  '@vitejs/plugin-react': ^5.0.3
  autoprefixer: 10.4.21
  electron: ^38.1.2
  electron-builder: ^26.0.12
  electron-updater: 6.6.2
  eslint: ^9.36.0
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.14
  globals: ^15.12.0
  lucide-react: 0.544.0
  postcss: ^8.4.47
  react: ^19.1.0
  react-dom: ^19.1.0
  tailwindcss: ^4.1.13
  tsup: ^8.5.0
  typescript: ^5.9.2
  vite: ^7.1.7
  vitest: ^3.2.4

ignoredBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - electron
  - electron-winstaller
  - esbuild
  - msw
