import type { Staff } from './types';

export const mockStaff: Staff[] = [
  {
    id: '1',
    name: '이수진',
    role: '헤어 디자이너',
    position: 'senior',
    phone: '010-1111-2222',
    email: 'sujin.lee@salon.com',
    hireDate: '2021-03-15',
    status: 'active',
    specialties: ['컷', '염색', '펌'],
    personalMemo:
      '고객 응대가 매우 친절하고 전문적입니다. 염색 기술이 특히 뛰어납니다.',
    monthlyCustomers: 45,
    monthlyServices: 68,
    workingDays: 240,
    annualLeaveUsed: 8,
    annualLeaveTotal: 15,
    holidays: [
      {
        id: 'h1',
        startDate: '2024-07-15',
        endDate: '2024-07-15',
        type: 'annual',
        isHalfDay: false,
        reason: '개인 사정',
        status: 'approved',
        appliedAt: '2024-07-10',
      },
      {
        id: 'h2',
        startDate: '2024-08-20',
        endDate: '2024-08-20',
        type: 'sick',
        isHalfDay: false,
        reason: '몸살감기',
        status: 'pending',
        appliedAt: '2024-08-18',
      },
    ],
  },
  {
    id: '2',
    name: '김하늘',
    role: '헤어 디자이너',
    position: 'manager',
    phone: '010-2222-3333',
    email: 'haneul.kim@salon.com',
    hireDate: '2020-05-20',
    status: 'active',
    specialties: ['컷', '염색', '트리트먼트'],
    personalMemo:
      '매장 관리와 고객 상담에 뛰어난 능력을 보입니다. 신입 직원 교육도 담당하고 있습니다.',
    monthlyCustomers: 38,
    monthlyServices: 52,
    workingDays: 280,
    annualLeaveUsed: 12,
    annualLeaveTotal: 20,
    holidays: [
      {
        id: 'h3',
        startDate: '2024-06-10',
        endDate: '2024-06-12',
        type: 'annual',
        isHalfDay: false,
        reason: '휴가',
        status: 'approved',
        appliedAt: '2024-06-01',
      },
    ],
  },
  {
    id: '3',
    name: '정미래',
    role: '네일 아티스트',
    position: 'senior',
    phone: '010-3333-4444',
    email: 'mirae.jung@salon.com',
    hireDate: '2022-01-10',
    status: 'active',
    specialties: ['젤네일', '네일아트', '페디큐어'],
    personalMemo:
      '네일 아트 실력이 뛰어나고 트렌드에 민감합니다. SNS 관리도 도움을 주고 있습니다.',
    monthlyCustomers: 52,
    monthlyServices: 75,
    workingDays: 180,
    annualLeaveUsed: 5,
    annualLeaveTotal: 15,
    holidays: [],
  },
  {
    id: '4',
    name: '박소영',
    role: '피부 관리사',
    position: 'junior',
    phone: '010-4444-5555',
    email: 'soyoung.park@salon.com',
    hireDate: '2023-08-01',
    status: 'active',
    specialties: ['페이셜', '마사지', '필링'],
    personalMemo: '성실하고 꼼꼼한 성격으로 고객들의 신뢰를 받고 있습니다.',
    monthlyCustomers: 31,
    monthlyServices: 42,
    workingDays: 120,
    annualLeaveUsed: 3,
    annualLeaveTotal: 15,
    holidays: [
      {
        id: 'h4',
        startDate: '2024-09-05',
        endDate: '2024-09-05',
        type: 'personal',
        isHalfDay: true,
        reason: '병원 진료',
        status: 'pending',
        appliedAt: '2024-09-01',
      },
    ],
  },
  {
    id: '5',
    name: '최은영',
    role: '어시스턴트',
    position: 'intern',
    phone: '010-5555-6666',
    email: 'eunyoung.choi@salon.com',
    hireDate: '2024-01-15',
    status: 'on_leave',
    specialties: ['샴푸', '보조업무'],
    personalMemo: '열정적이고 배우려는 의지가 강합니다. 현재 휴직 중입니다.',
    monthlyCustomers: 0,
    monthlyServices: 0,
    workingDays: 80,
    annualLeaveUsed: 0,
    annualLeaveTotal: 10,
    holidays: [
      {
        id: 'h5',
        startDate: '2024-08-01',
        endDate: '2024-08-31',
        type: 'personal',
        isHalfDay: false,
        reason: '개인 사정으로 인한 장기 휴직',
        status: 'approved',
        appliedAt: '2024-07-20',
      },
    ],
  },
];
